package com.loop0day.security.db.bean;

public class AttackModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attack_model.vuln_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer vulnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attack_model.vuln_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String vulnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attack_model.pre_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer prePrivilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attack_model.fin_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer finPrivilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attack_model.used_flag
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer usedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public AttackModel(Integer vulnId, String vulnName, Integer prePrivilegeId, Integer finPrivilegeId, Integer usedFlag) {
        this.vulnId = vulnId;
        this.vulnName = vulnName;
        this.prePrivilegeId = prePrivilegeId;
        this.finPrivilegeId = finPrivilegeId;
        this.usedFlag = usedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public AttackModel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attack_model.vuln_id
     *
     * @return the value of attack_model.vuln_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getVulnId() {
        return vulnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attack_model.vuln_id
     *
     * @param vulnId the value for attack_model.vuln_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setVulnId(Integer vulnId) {
        this.vulnId = vulnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attack_model.vuln_name
     *
     * @return the value of attack_model.vuln_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getVulnName() {
        return vulnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attack_model.vuln_name
     *
     * @param vulnName the value for attack_model.vuln_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setVulnName(String vulnName) {
        this.vulnName = vulnName == null ? null : vulnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attack_model.pre_privilege_id
     *
     * @return the value of attack_model.pre_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getPrePrivilegeId() {
        return prePrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attack_model.pre_privilege_id
     *
     * @param prePrivilegeId the value for attack_model.pre_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPrePrivilegeId(Integer prePrivilegeId) {
        this.prePrivilegeId = prePrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attack_model.fin_privilege_id
     *
     * @return the value of attack_model.fin_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getFinPrivilegeId() {
        return finPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attack_model.fin_privilege_id
     *
     * @param finPrivilegeId the value for attack_model.fin_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setFinPrivilegeId(Integer finPrivilegeId) {
        this.finPrivilegeId = finPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attack_model.used_flag
     *
     * @return the value of attack_model.used_flag
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getUsedFlag() {
        return usedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attack_model.used_flag
     *
     * @param usedFlag the value for attack_model.used_flag
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setUsedFlag(Integer usedFlag) {
        this.usedFlag = usedFlag;
    }
}