package com.loop0day.security.db.bean;

import java.util.ArrayList;
import java.util.List;

public class AttackModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public AttackModelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVulnIdIsNull() {
            addCriterion("vuln_id is null");
            return (Criteria) this;
        }

        public Criteria andVulnIdIsNotNull() {
            addCriterion("vuln_id is not null");
            return (Criteria) this;
        }

        public Criteria andVulnIdEqualTo(Integer value) {
            addCriterion("vuln_id =", value, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdNotEqualTo(Integer value) {
            addCriterion("vuln_id <>", value, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdGreaterThan(Integer value) {
            addCriterion("vuln_id >", value, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vuln_id >=", value, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdLessThan(Integer value) {
            addCriterion("vuln_id <", value, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdLessThanOrEqualTo(Integer value) {
            addCriterion("vuln_id <=", value, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdIn(List<Integer> values) {
            addCriterion("vuln_id in", values, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdNotIn(List<Integer> values) {
            addCriterion("vuln_id not in", values, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdBetween(Integer value1, Integer value2) {
            addCriterion("vuln_id between", value1, value2, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vuln_id not between", value1, value2, "vulnId");
            return (Criteria) this;
        }

        public Criteria andVulnNameIsNull() {
            addCriterion("vuln_name is null");
            return (Criteria) this;
        }

        public Criteria andVulnNameIsNotNull() {
            addCriterion("vuln_name is not null");
            return (Criteria) this;
        }

        public Criteria andVulnNameEqualTo(String value) {
            addCriterion("vuln_name =", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameNotEqualTo(String value) {
            addCriterion("vuln_name <>", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameGreaterThan(String value) {
            addCriterion("vuln_name >", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameGreaterThanOrEqualTo(String value) {
            addCriterion("vuln_name >=", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameLessThan(String value) {
            addCriterion("vuln_name <", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameLessThanOrEqualTo(String value) {
            addCriterion("vuln_name <=", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameLike(String value) {
            addCriterion("vuln_name like", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameNotLike(String value) {
            addCriterion("vuln_name not like", value, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameIn(List<String> values) {
            addCriterion("vuln_name in", values, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameNotIn(List<String> values) {
            addCriterion("vuln_name not in", values, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameBetween(String value1, String value2) {
            addCriterion("vuln_name between", value1, value2, "vulnName");
            return (Criteria) this;
        }

        public Criteria andVulnNameNotBetween(String value1, String value2) {
            addCriterion("vuln_name not between", value1, value2, "vulnName");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdIsNull() {
            addCriterion("pre_privilege_id is null");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdIsNotNull() {
            addCriterion("pre_privilege_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdEqualTo(Integer value) {
            addCriterion("pre_privilege_id =", value, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdNotEqualTo(Integer value) {
            addCriterion("pre_privilege_id <>", value, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdGreaterThan(Integer value) {
            addCriterion("pre_privilege_id >", value, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pre_privilege_id >=", value, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdLessThan(Integer value) {
            addCriterion("pre_privilege_id <", value, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdLessThanOrEqualTo(Integer value) {
            addCriterion("pre_privilege_id <=", value, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdIn(List<Integer> values) {
            addCriterion("pre_privilege_id in", values, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdNotIn(List<Integer> values) {
            addCriterion("pre_privilege_id not in", values, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdBetween(Integer value1, Integer value2) {
            addCriterion("pre_privilege_id between", value1, value2, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andPrePrivilegeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pre_privilege_id not between", value1, value2, "prePrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdIsNull() {
            addCriterion("fin_privilege_id is null");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdIsNotNull() {
            addCriterion("fin_privilege_id is not null");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdEqualTo(Integer value) {
            addCriterion("fin_privilege_id =", value, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdNotEqualTo(Integer value) {
            addCriterion("fin_privilege_id <>", value, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdGreaterThan(Integer value) {
            addCriterion("fin_privilege_id >", value, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fin_privilege_id >=", value, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdLessThan(Integer value) {
            addCriterion("fin_privilege_id <", value, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdLessThanOrEqualTo(Integer value) {
            addCriterion("fin_privilege_id <=", value, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdIn(List<Integer> values) {
            addCriterion("fin_privilege_id in", values, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdNotIn(List<Integer> values) {
            addCriterion("fin_privilege_id not in", values, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdBetween(Integer value1, Integer value2) {
            addCriterion("fin_privilege_id between", value1, value2, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andFinPrivilegeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fin_privilege_id not between", value1, value2, "finPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andUsedFlagIsNull() {
            addCriterion("used_flag is null");
            return (Criteria) this;
        }

        public Criteria andUsedFlagIsNotNull() {
            addCriterion("used_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUsedFlagEqualTo(Integer value) {
            addCriterion("used_flag =", value, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagNotEqualTo(Integer value) {
            addCriterion("used_flag <>", value, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagGreaterThan(Integer value) {
            addCriterion("used_flag >", value, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("used_flag >=", value, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagLessThan(Integer value) {
            addCriterion("used_flag <", value, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagLessThanOrEqualTo(Integer value) {
            addCriterion("used_flag <=", value, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagIn(List<Integer> values) {
            addCriterion("used_flag in", values, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagNotIn(List<Integer> values) {
            addCriterion("used_flag not in", values, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagBetween(Integer value1, Integer value2) {
            addCriterion("used_flag between", value1, value2, "usedFlag");
            return (Criteria) this;
        }

        public Criteria andUsedFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("used_flag not between", value1, value2, "usedFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attack_model
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 03 17:43:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}