package com.loop0day.security.db.bean;

public class DevicePrivilege extends DevicePrivilegeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_privilege.data
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_privilege.comment
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DevicePrivilege(Integer privilegeId, Integer deviceId, Integer serviceId, String data, String comment) {
        super(privilegeId, deviceId, serviceId);
        this.data = data;
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DevicePrivilege() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_privilege.data
     *
     * @return the value of device_privilege.data
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_privilege.data
     *
     * @param data the value for device_privilege.data
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_privilege.comment
     *
     * @return the value of device_privilege.comment
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_privilege.comment
     *
     * @param comment the value for device_privilege.comment
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}