package com.loop0day.security.db.bean;

public class DeviceServiceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_service.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_service.service_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer serviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceServiceKey(Integer deviceId, Integer serviceId) {
        this.deviceId = deviceId;
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceServiceKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_service.device_id
     *
     * @return the value of device_service.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_service.device_id
     *
     * @param deviceId the value for device_service.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_service.service_id
     *
     * @return the value of device_service.service_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_service.service_id
     *
     * @param serviceId the value for device_service.service_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }
}