package com.loop0day.security.db.bean;

public class DeviceDataflowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.type
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.src
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.sport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String sport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.dst
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String dst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.dport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String dport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String protocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer variantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceDataflowKey(Integer deviceId, String type, Integer privilegeId, String src, String sport, String dst, String dport, String protocol, Integer variantId) {
        this.deviceId = deviceId;
        this.type = type;
        this.privilegeId = privilegeId;
        this.src = src;
        this.sport = sport;
        this.dst = dst;
        this.dport = dport;
        this.protocol = protocol;
        this.variantId = variantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceDataflowKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.device_id
     *
     * @return the value of device_dataflow.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.device_id
     *
     * @param deviceId the value for device_dataflow.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.type
     *
     * @return the value of device_dataflow.type
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.type
     *
     * @param type the value for device_dataflow.type
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.privilege_id
     *
     * @return the value of device_dataflow.privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.privilege_id
     *
     * @param privilegeId the value for device_dataflow.privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.src
     *
     * @return the value of device_dataflow.src
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.src
     *
     * @param src the value for device_dataflow.src
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.sport
     *
     * @return the value of device_dataflow.sport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.sport
     *
     * @param sport the value for device_dataflow.sport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setSport(String sport) {
        this.sport = sport == null ? null : sport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.dst
     *
     * @return the value of device_dataflow.dst
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getDst() {
        return dst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.dst
     *
     * @param dst the value for device_dataflow.dst
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDst(String dst) {
        this.dst = dst == null ? null : dst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.dport
     *
     * @return the value of device_dataflow.dport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getDport() {
        return dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.dport
     *
     * @param dport the value for device_dataflow.dport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDport(String dport) {
        this.dport = dport == null ? null : dport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.protocol
     *
     * @return the value of device_dataflow.protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.protocol
     *
     * @param protocol the value for device_dataflow.protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.variant_id
     *
     * @return the value of device_dataflow.variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getVariantId() {
        return variantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.variant_id
     *
     * @param variantId the value for device_dataflow.variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setVariantId(Integer variantId) {
        this.variantId = variantId;
    }
}