package com.loop0day.security.db.bean;

public class DeviceConnect extends DeviceConnectKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_connect.peer_device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer peerDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_connect.peer_interface_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer peerInterfaceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceConnect(Integer deviceId, Integer interfaceId, Integer peerDeviceId, Integer peerInterfaceId) {
        super(deviceId, interfaceId);
        this.peerDeviceId = peerDeviceId;
        this.peerInterfaceId = peerInterfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceConnect() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_connect.peer_device_id
     *
     * @return the value of device_connect.peer_device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getPeerDeviceId() {
        return peerDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_connect.peer_device_id
     *
     * @param peerDeviceId the value for device_connect.peer_device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPeerDeviceId(Integer peerDeviceId) {
        this.peerDeviceId = peerDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_connect.peer_interface_id
     *
     * @return the value of device_connect.peer_interface_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getPeerInterfaceId() {
        return peerInterfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_connect.peer_interface_id
     *
     * @param peerInterfaceId the value for device_connect.peer_interface_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPeerInterfaceId(Integer peerInterfaceId) {
        this.peerInterfaceId = peerInterfaceId;
    }
}