package com.loop0day.security.db.bean;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_type
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_deploy
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceDeploy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_value
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Double deviceValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Device(Integer deviceId, String deviceName, String deviceType, Integer deviceDeploy, Double deviceValue) {
        this.deviceId = deviceId;
        this.deviceName = deviceName;
        this.deviceType = deviceType;
        this.deviceDeploy = deviceDeploy;
        this.deviceValue = deviceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Device() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_name
     *
     * @return the value of device.device_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_name
     *
     * @param deviceName the value for device.device_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_type
     *
     * @return the value of device.device_type
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_type
     *
     * @param deviceType the value for device.device_type
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_deploy
     *
     * @return the value of device.device_deploy
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceDeploy() {
        return deviceDeploy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_deploy
     *
     * @param deviceDeploy the value for device.device_deploy
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceDeploy(Integer deviceDeploy) {
        this.deviceDeploy = deviceDeploy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_value
     *
     * @return the value of device.device_value
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Double getDeviceValue() {
        return deviceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_value
     *
     * @param deviceValue the value for device.device_value
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceValue(Double deviceValue) {
        this.deviceValue = deviceValue;
    }
}