package com.loop0day.security.db.bean;

public class DeviceSecurityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_security.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_security.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_security.owner_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer ownerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceSecurityKey(Integer deviceId, Integer functionId, Integer ownerId) {
        this.deviceId = deviceId;
        this.functionId = functionId;
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceSecurityKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_security.device_id
     *
     * @return the value of device_security.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_security.device_id
     *
     * @param deviceId the value for device_security.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_security.function_id
     *
     * @return the value of device_security.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_security.function_id
     *
     * @param functionId the value for device_security.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_security.owner_id
     *
     * @return the value of device_security.owner_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_security.owner_id
     *
     * @param ownerId the value for device_security.owner_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }
}