package com.loop0day.security.db.bean;

import java.util.ArrayList;
import java.util.List;

public class DeviceDataflowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceDataflowExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Integer value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Integer value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Integer value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Integer value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Integer> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Integer> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdIsNull() {
            addCriterion("privilege_id is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdIsNotNull() {
            addCriterion("privilege_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdEqualTo(Integer value) {
            addCriterion("privilege_id =", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdNotEqualTo(Integer value) {
            addCriterion("privilege_id <>", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdGreaterThan(Integer value) {
            addCriterion("privilege_id >", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("privilege_id >=", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdLessThan(Integer value) {
            addCriterion("privilege_id <", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdLessThanOrEqualTo(Integer value) {
            addCriterion("privilege_id <=", value, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdIn(List<Integer> values) {
            addCriterion("privilege_id in", values, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdNotIn(List<Integer> values) {
            addCriterion("privilege_id not in", values, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdBetween(Integer value1, Integer value2) {
            addCriterion("privilege_id between", value1, value2, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andPrivilegeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("privilege_id not between", value1, value2, "privilegeId");
            return (Criteria) this;
        }

        public Criteria andSrcIsNull() {
            addCriterion("src is null");
            return (Criteria) this;
        }

        public Criteria andSrcIsNotNull() {
            addCriterion("src is not null");
            return (Criteria) this;
        }

        public Criteria andSrcEqualTo(String value) {
            addCriterion("src =", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotEqualTo(String value) {
            addCriterion("src <>", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcGreaterThan(String value) {
            addCriterion("src >", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcGreaterThanOrEqualTo(String value) {
            addCriterion("src >=", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLessThan(String value) {
            addCriterion("src <", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLessThanOrEqualTo(String value) {
            addCriterion("src <=", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcLike(String value) {
            addCriterion("src like", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotLike(String value) {
            addCriterion("src not like", value, "src");
            return (Criteria) this;
        }

        public Criteria andSrcIn(List<String> values) {
            addCriterion("src in", values, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotIn(List<String> values) {
            addCriterion("src not in", values, "src");
            return (Criteria) this;
        }

        public Criteria andSrcBetween(String value1, String value2) {
            addCriterion("src between", value1, value2, "src");
            return (Criteria) this;
        }

        public Criteria andSrcNotBetween(String value1, String value2) {
            addCriterion("src not between", value1, value2, "src");
            return (Criteria) this;
        }

        public Criteria andSportIsNull() {
            addCriterion("sport is null");
            return (Criteria) this;
        }

        public Criteria andSportIsNotNull() {
            addCriterion("sport is not null");
            return (Criteria) this;
        }

        public Criteria andSportEqualTo(String value) {
            addCriterion("sport =", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportNotEqualTo(String value) {
            addCriterion("sport <>", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportGreaterThan(String value) {
            addCriterion("sport >", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportGreaterThanOrEqualTo(String value) {
            addCriterion("sport >=", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportLessThan(String value) {
            addCriterion("sport <", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportLessThanOrEqualTo(String value) {
            addCriterion("sport <=", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportLike(String value) {
            addCriterion("sport like", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportNotLike(String value) {
            addCriterion("sport not like", value, "sport");
            return (Criteria) this;
        }

        public Criteria andSportIn(List<String> values) {
            addCriterion("sport in", values, "sport");
            return (Criteria) this;
        }

        public Criteria andSportNotIn(List<String> values) {
            addCriterion("sport not in", values, "sport");
            return (Criteria) this;
        }

        public Criteria andSportBetween(String value1, String value2) {
            addCriterion("sport between", value1, value2, "sport");
            return (Criteria) this;
        }

        public Criteria andSportNotBetween(String value1, String value2) {
            addCriterion("sport not between", value1, value2, "sport");
            return (Criteria) this;
        }

        public Criteria andDstIsNull() {
            addCriterion("dst is null");
            return (Criteria) this;
        }

        public Criteria andDstIsNotNull() {
            addCriterion("dst is not null");
            return (Criteria) this;
        }

        public Criteria andDstEqualTo(String value) {
            addCriterion("dst =", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstNotEqualTo(String value) {
            addCriterion("dst <>", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstGreaterThan(String value) {
            addCriterion("dst >", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstGreaterThanOrEqualTo(String value) {
            addCriterion("dst >=", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstLessThan(String value) {
            addCriterion("dst <", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstLessThanOrEqualTo(String value) {
            addCriterion("dst <=", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstLike(String value) {
            addCriterion("dst like", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstNotLike(String value) {
            addCriterion("dst not like", value, "dst");
            return (Criteria) this;
        }

        public Criteria andDstIn(List<String> values) {
            addCriterion("dst in", values, "dst");
            return (Criteria) this;
        }

        public Criteria andDstNotIn(List<String> values) {
            addCriterion("dst not in", values, "dst");
            return (Criteria) this;
        }

        public Criteria andDstBetween(String value1, String value2) {
            addCriterion("dst between", value1, value2, "dst");
            return (Criteria) this;
        }

        public Criteria andDstNotBetween(String value1, String value2) {
            addCriterion("dst not between", value1, value2, "dst");
            return (Criteria) this;
        }

        public Criteria andDportIsNull() {
            addCriterion("dport is null");
            return (Criteria) this;
        }

        public Criteria andDportIsNotNull() {
            addCriterion("dport is not null");
            return (Criteria) this;
        }

        public Criteria andDportEqualTo(String value) {
            addCriterion("dport =", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportNotEqualTo(String value) {
            addCriterion("dport <>", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportGreaterThan(String value) {
            addCriterion("dport >", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportGreaterThanOrEqualTo(String value) {
            addCriterion("dport >=", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportLessThan(String value) {
            addCriterion("dport <", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportLessThanOrEqualTo(String value) {
            addCriterion("dport <=", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportLike(String value) {
            addCriterion("dport like", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportNotLike(String value) {
            addCriterion("dport not like", value, "dport");
            return (Criteria) this;
        }

        public Criteria andDportIn(List<String> values) {
            addCriterion("dport in", values, "dport");
            return (Criteria) this;
        }

        public Criteria andDportNotIn(List<String> values) {
            addCriterion("dport not in", values, "dport");
            return (Criteria) this;
        }

        public Criteria andDportBetween(String value1, String value2) {
            addCriterion("dport between", value1, value2, "dport");
            return (Criteria) this;
        }

        public Criteria andDportNotBetween(String value1, String value2) {
            addCriterion("dport not between", value1, value2, "dport");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNull() {
            addCriterion("protocol is null");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNotNull() {
            addCriterion("protocol is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolEqualTo(String value) {
            addCriterion("protocol =", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotEqualTo(String value) {
            addCriterion("protocol <>", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThan(String value) {
            addCriterion("protocol >", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThanOrEqualTo(String value) {
            addCriterion("protocol >=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThan(String value) {
            addCriterion("protocol <", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThanOrEqualTo(String value) {
            addCriterion("protocol <=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLike(String value) {
            addCriterion("protocol like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotLike(String value) {
            addCriterion("protocol not like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolIn(List<String> values) {
            addCriterion("protocol in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotIn(List<String> values) {
            addCriterion("protocol not in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolBetween(String value1, String value2) {
            addCriterion("protocol between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotBetween(String value1, String value2) {
            addCriterion("protocol not between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andVariantIdIsNull() {
            addCriterion("variant_id is null");
            return (Criteria) this;
        }

        public Criteria andVariantIdIsNotNull() {
            addCriterion("variant_id is not null");
            return (Criteria) this;
        }

        public Criteria andVariantIdEqualTo(Integer value) {
            addCriterion("variant_id =", value, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdNotEqualTo(Integer value) {
            addCriterion("variant_id <>", value, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdGreaterThan(Integer value) {
            addCriterion("variant_id >", value, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("variant_id >=", value, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdLessThan(Integer value) {
            addCriterion("variant_id <", value, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdLessThanOrEqualTo(Integer value) {
            addCriterion("variant_id <=", value, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdIn(List<Integer> values) {
            addCriterion("variant_id in", values, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdNotIn(List<Integer> values) {
            addCriterion("variant_id not in", values, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdBetween(Integer value1, Integer value2) {
            addCriterion("variant_id between", value1, value2, "variantId");
            return (Criteria) this;
        }

        public Criteria andVariantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("variant_id not between", value1, value2, "variantId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdIsNull() {
            addCriterion("t_privilege_id is null");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdIsNotNull() {
            addCriterion("t_privilege_id is not null");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdEqualTo(Integer value) {
            addCriterion("t_privilege_id =", value, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdNotEqualTo(Integer value) {
            addCriterion("t_privilege_id <>", value, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdGreaterThan(Integer value) {
            addCriterion("t_privilege_id >", value, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("t_privilege_id >=", value, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdLessThan(Integer value) {
            addCriterion("t_privilege_id <", value, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdLessThanOrEqualTo(Integer value) {
            addCriterion("t_privilege_id <=", value, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdIn(List<Integer> values) {
            addCriterion("t_privilege_id in", values, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdNotIn(List<Integer> values) {
            addCriterion("t_privilege_id not in", values, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdBetween(Integer value1, Integer value2) {
            addCriterion("t_privilege_id between", value1, value2, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTPrivilegeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("t_privilege_id not between", value1, value2, "tPrivilegeId");
            return (Criteria) this;
        }

        public Criteria andTSrcIsNull() {
            addCriterion("t_src is null");
            return (Criteria) this;
        }

        public Criteria andTSrcIsNotNull() {
            addCriterion("t_src is not null");
            return (Criteria) this;
        }

        public Criteria andTSrcEqualTo(String value) {
            addCriterion("t_src =", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcNotEqualTo(String value) {
            addCriterion("t_src <>", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcGreaterThan(String value) {
            addCriterion("t_src >", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcGreaterThanOrEqualTo(String value) {
            addCriterion("t_src >=", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcLessThan(String value) {
            addCriterion("t_src <", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcLessThanOrEqualTo(String value) {
            addCriterion("t_src <=", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcLike(String value) {
            addCriterion("t_src like", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcNotLike(String value) {
            addCriterion("t_src not like", value, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcIn(List<String> values) {
            addCriterion("t_src in", values, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcNotIn(List<String> values) {
            addCriterion("t_src not in", values, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcBetween(String value1, String value2) {
            addCriterion("t_src between", value1, value2, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSrcNotBetween(String value1, String value2) {
            addCriterion("t_src not between", value1, value2, "tSrc");
            return (Criteria) this;
        }

        public Criteria andTSportIsNull() {
            addCriterion("t_sport is null");
            return (Criteria) this;
        }

        public Criteria andTSportIsNotNull() {
            addCriterion("t_sport is not null");
            return (Criteria) this;
        }

        public Criteria andTSportEqualTo(String value) {
            addCriterion("t_sport =", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportNotEqualTo(String value) {
            addCriterion("t_sport <>", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportGreaterThan(String value) {
            addCriterion("t_sport >", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportGreaterThanOrEqualTo(String value) {
            addCriterion("t_sport >=", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportLessThan(String value) {
            addCriterion("t_sport <", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportLessThanOrEqualTo(String value) {
            addCriterion("t_sport <=", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportLike(String value) {
            addCriterion("t_sport like", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportNotLike(String value) {
            addCriterion("t_sport not like", value, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportIn(List<String> values) {
            addCriterion("t_sport in", values, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportNotIn(List<String> values) {
            addCriterion("t_sport not in", values, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportBetween(String value1, String value2) {
            addCriterion("t_sport between", value1, value2, "tSport");
            return (Criteria) this;
        }

        public Criteria andTSportNotBetween(String value1, String value2) {
            addCriterion("t_sport not between", value1, value2, "tSport");
            return (Criteria) this;
        }

        public Criteria andTDstIsNull() {
            addCriterion("t_dst is null");
            return (Criteria) this;
        }

        public Criteria andTDstIsNotNull() {
            addCriterion("t_dst is not null");
            return (Criteria) this;
        }

        public Criteria andTDstEqualTo(String value) {
            addCriterion("t_dst =", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstNotEqualTo(String value) {
            addCriterion("t_dst <>", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstGreaterThan(String value) {
            addCriterion("t_dst >", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstGreaterThanOrEqualTo(String value) {
            addCriterion("t_dst >=", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstLessThan(String value) {
            addCriterion("t_dst <", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstLessThanOrEqualTo(String value) {
            addCriterion("t_dst <=", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstLike(String value) {
            addCriterion("t_dst like", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstNotLike(String value) {
            addCriterion("t_dst not like", value, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstIn(List<String> values) {
            addCriterion("t_dst in", values, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstNotIn(List<String> values) {
            addCriterion("t_dst not in", values, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstBetween(String value1, String value2) {
            addCriterion("t_dst between", value1, value2, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDstNotBetween(String value1, String value2) {
            addCriterion("t_dst not between", value1, value2, "tDst");
            return (Criteria) this;
        }

        public Criteria andTDportIsNull() {
            addCriterion("t_dport is null");
            return (Criteria) this;
        }

        public Criteria andTDportIsNotNull() {
            addCriterion("t_dport is not null");
            return (Criteria) this;
        }

        public Criteria andTDportEqualTo(String value) {
            addCriterion("t_dport =", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportNotEqualTo(String value) {
            addCriterion("t_dport <>", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportGreaterThan(String value) {
            addCriterion("t_dport >", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportGreaterThanOrEqualTo(String value) {
            addCriterion("t_dport >=", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportLessThan(String value) {
            addCriterion("t_dport <", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportLessThanOrEqualTo(String value) {
            addCriterion("t_dport <=", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportLike(String value) {
            addCriterion("t_dport like", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportNotLike(String value) {
            addCriterion("t_dport not like", value, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportIn(List<String> values) {
            addCriterion("t_dport in", values, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportNotIn(List<String> values) {
            addCriterion("t_dport not in", values, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportBetween(String value1, String value2) {
            addCriterion("t_dport between", value1, value2, "tDport");
            return (Criteria) this;
        }

        public Criteria andTDportNotBetween(String value1, String value2) {
            addCriterion("t_dport not between", value1, value2, "tDport");
            return (Criteria) this;
        }

        public Criteria andTProtocolIsNull() {
            addCriterion("t_protocol is null");
            return (Criteria) this;
        }

        public Criteria andTProtocolIsNotNull() {
            addCriterion("t_protocol is not null");
            return (Criteria) this;
        }

        public Criteria andTProtocolEqualTo(String value) {
            addCriterion("t_protocol =", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolNotEqualTo(String value) {
            addCriterion("t_protocol <>", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolGreaterThan(String value) {
            addCriterion("t_protocol >", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolGreaterThanOrEqualTo(String value) {
            addCriterion("t_protocol >=", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolLessThan(String value) {
            addCriterion("t_protocol <", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolLessThanOrEqualTo(String value) {
            addCriterion("t_protocol <=", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolLike(String value) {
            addCriterion("t_protocol like", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolNotLike(String value) {
            addCriterion("t_protocol not like", value, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolIn(List<String> values) {
            addCriterion("t_protocol in", values, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolNotIn(List<String> values) {
            addCriterion("t_protocol not in", values, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolBetween(String value1, String value2) {
            addCriterion("t_protocol between", value1, value2, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTProtocolNotBetween(String value1, String value2) {
            addCriterion("t_protocol not between", value1, value2, "tProtocol");
            return (Criteria) this;
        }

        public Criteria andTVariantIdIsNull() {
            addCriterion("t_variant_id is null");
            return (Criteria) this;
        }

        public Criteria andTVariantIdIsNotNull() {
            addCriterion("t_variant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTVariantIdEqualTo(Integer value) {
            addCriterion("t_variant_id =", value, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdNotEqualTo(Integer value) {
            addCriterion("t_variant_id <>", value, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdGreaterThan(Integer value) {
            addCriterion("t_variant_id >", value, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("t_variant_id >=", value, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdLessThan(Integer value) {
            addCriterion("t_variant_id <", value, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdLessThanOrEqualTo(Integer value) {
            addCriterion("t_variant_id <=", value, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdIn(List<Integer> values) {
            addCriterion("t_variant_id in", values, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdNotIn(List<Integer> values) {
            addCriterion("t_variant_id not in", values, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdBetween(Integer value1, Integer value2) {
            addCriterion("t_variant_id between", value1, value2, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andTVariantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("t_variant_id not between", value1, value2, "tVariantId");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_dataflow
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 03 17:43:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}