package com.loop0day.security.db.bean;

public class DeviceRoute extends DeviceRouteKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_route.gateway
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String gateway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_route.interface_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer interfaceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_route
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceRoute(Integer deviceId, String destination, String genmask, String gateway, Integer interfaceId) {
        super(deviceId, destination, genmask);
        this.gateway = gateway;
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_route
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceRoute() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_route.gateway
     *
     * @return the value of device_route.gateway
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_route.gateway
     *
     * @param gateway the value for device_route.gateway
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setGateway(String gateway) {
        this.gateway = gateway == null ? null : gateway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_route.interface_id
     *
     * @return the value of device_route.interface_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_route.interface_id
     *
     * @param interfaceId the value for device_route.interface_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }
}