package com.loop0day.security.db.bean;

public class DeviceService extends DeviceServiceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_service.environment
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String environment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_service.port
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_service.service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String service;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_service.protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String protocol;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceService(Integer deviceId, Integer serviceId, String environment, String port, String service, String protocol) {
        super(deviceId, serviceId);
        this.environment = environment;
        this.port = port;
        this.service = service;
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceService() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_service.environment
     *
     * @return the value of device_service.environment
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_service.environment
     *
     * @param environment the value for device_service.environment
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setEnvironment(String environment) {
        this.environment = environment == null ? null : environment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_service.port
     *
     * @return the value of device_service.port
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_service.port
     *
     * @param port the value for device_service.port
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_service.service
     *
     * @return the value of device_service.service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_service.service
     *
     * @param service the value for device_service.service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_service.protocol
     *
     * @return the value of device_service.protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_service.protocol
     *
     * @param protocol the value for device_service.protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }
}