package com.loop0day.security.db.bean;

public class DeviceDataflow extends DeviceDataflowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer tPrivilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_src
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String tSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_sport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String tSport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_dst
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String tDst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_dport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String tDport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String tProtocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.t_variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer tVariantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_dataflow.priority
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceDataflow(Integer deviceId, String type, Integer privilegeId, String src, String sport, String dst, String dport, String protocol, Integer variantId, Integer tPrivilegeId, String tSrc, String tSport, String tDst, String tDport, String tProtocol, Integer tVariantId, Integer priority) {
        super(deviceId, type, privilegeId, src, sport, dst, dport, protocol, variantId);
        this.tPrivilegeId = tPrivilegeId;
        this.tSrc = tSrc;
        this.tSport = tSport;
        this.tDst = tDst;
        this.tDport = tDport;
        this.tProtocol = tProtocol;
        this.tVariantId = tVariantId;
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public DeviceDataflow() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_privilege_id
     *
     * @return the value of device_dataflow.t_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer gettPrivilegeId() {
        return tPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_privilege_id
     *
     * @param tPrivilegeId the value for device_dataflow.t_privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settPrivilegeId(Integer tPrivilegeId) {
        this.tPrivilegeId = tPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_src
     *
     * @return the value of device_dataflow.t_src
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String gettSrc() {
        return tSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_src
     *
     * @param tSrc the value for device_dataflow.t_src
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settSrc(String tSrc) {
        this.tSrc = tSrc == null ? null : tSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_sport
     *
     * @return the value of device_dataflow.t_sport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String gettSport() {
        return tSport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_sport
     *
     * @param tSport the value for device_dataflow.t_sport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settSport(String tSport) {
        this.tSport = tSport == null ? null : tSport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_dst
     *
     * @return the value of device_dataflow.t_dst
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String gettDst() {
        return tDst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_dst
     *
     * @param tDst the value for device_dataflow.t_dst
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settDst(String tDst) {
        this.tDst = tDst == null ? null : tDst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_dport
     *
     * @return the value of device_dataflow.t_dport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String gettDport() {
        return tDport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_dport
     *
     * @param tDport the value for device_dataflow.t_dport
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settDport(String tDport) {
        this.tDport = tDport == null ? null : tDport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_protocol
     *
     * @return the value of device_dataflow.t_protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String gettProtocol() {
        return tProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_protocol
     *
     * @param tProtocol the value for device_dataflow.t_protocol
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settProtocol(String tProtocol) {
        this.tProtocol = tProtocol == null ? null : tProtocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.t_variant_id
     *
     * @return the value of device_dataflow.t_variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer gettVariantId() {
        return tVariantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.t_variant_id
     *
     * @param tVariantId the value for device_dataflow.t_variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void settVariantId(Integer tVariantId) {
        this.tVariantId = tVariantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_dataflow.priority
     *
     * @return the value of device_dataflow.priority
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_dataflow.priority
     *
     * @param priority the value for device_dataflow.priority
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}