package com.loop0day.security.db.bean;

public class SecurityThreat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_threat.threat_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer threatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_threat.threat_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String threatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_threat.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SecurityThreat(Integer threatId, String threatName, Integer functionId) {
        this.threatId = threatId;
        this.threatName = threatName;
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SecurityThreat() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_threat.threat_id
     *
     * @return the value of security_threat.threat_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getThreatId() {
        return threatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_threat.threat_id
     *
     * @param threatId the value for security_threat.threat_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setThreatId(Integer threatId) {
        this.threatId = threatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_threat.threat_name
     *
     * @return the value of security_threat.threat_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getThreatName() {
        return threatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_threat.threat_name
     *
     * @param threatName the value for security_threat.threat_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setThreatName(String threatName) {
        this.threatName = threatName == null ? null : threatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_threat.function_id
     *
     * @return the value of security_threat.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_threat.function_id
     *
     * @param functionId the value for security_threat.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }
}