package com.loop0day.security.db.bean;

public class SecurityFunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_function.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_function.function_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String functionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_function.security_class
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private String securityClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_function
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SecurityFunction(Integer functionId, String functionName, String securityClass) {
        this.functionId = functionId;
        this.functionName = functionName;
        this.securityClass = securityClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_function
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SecurityFunction() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_function.function_id
     *
     * @return the value of security_function.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_function.function_id
     *
     * @param functionId the value for security_function.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_function.function_name
     *
     * @return the value of security_function.function_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_function.function_name
     *
     * @param functionName the value for security_function.function_name
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_function.security_class
     *
     * @return the value of security_function.security_class
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public String getSecurityClass() {
        return securityClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_function.security_class
     *
     * @param securityClass the value for security_function.security_class
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setSecurityClass(String securityClass) {
        this.securityClass = securityClass == null ? null : securityClass.trim();
    }
}