package com.loop0day.security.db.bean;

public class SingleTest extends SingleTestKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.record
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Double record;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.detect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Double detect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.alarm
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Double alarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.block
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Double block;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SingleTest(Integer deviceId, Integer functionId, Integer threatId, Integer variantId, Double record, Double detect, Double alarm, Double block) {
        super(deviceId, functionId, threatId, variantId);
        this.record = record;
        this.detect = detect;
        this.alarm = alarm;
        this.block = block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SingleTest() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.record
     *
     * @return the value of single_test.record
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Double getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.record
     *
     * @param record the value for single_test.record
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setRecord(Double record) {
        this.record = record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.detect
     *
     * @return the value of single_test.detect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Double getDetect() {
        return detect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.detect
     *
     * @param detect the value for single_test.detect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDetect(Double detect) {
        this.detect = detect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.alarm
     *
     * @return the value of single_test.alarm
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Double getAlarm() {
        return alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.alarm
     *
     * @param alarm the value for single_test.alarm
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setAlarm(Double alarm) {
        this.alarm = alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.block
     *
     * @return the value of single_test.block
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Double getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.block
     *
     * @param block the value for single_test.block
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setBlock(Double block) {
        this.block = block;
    }
}