package com.loop0day.security.db.bean;

public class SingleTestKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.threat_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer threatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_test.variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer variantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SingleTestKey(Integer deviceId, Integer functionId, Integer threatId, Integer variantId) {
        this.deviceId = deviceId;
        this.functionId = functionId;
        this.threatId = threatId;
        this.variantId = variantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public SingleTestKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.device_id
     *
     * @return the value of single_test.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.device_id
     *
     * @param deviceId the value for single_test.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.function_id
     *
     * @return the value of single_test.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.function_id
     *
     * @param functionId the value for single_test.function_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.threat_id
     *
     * @return the value of single_test.threat_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getThreatId() {
        return threatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.threat_id
     *
     * @param threatId the value for single_test.threat_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setThreatId(Integer threatId) {
        this.threatId = threatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_test.variant_id
     *
     * @return the value of single_test.variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getVariantId() {
        return variantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_test.variant_id
     *
     * @param variantId the value for single_test.variant_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setVariantId(Integer variantId) {
        this.variantId = variantId;
    }
}