package com.loop0day.security.db.bean;

public class UserPrivilegeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_privilege.privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_privilege.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_privilege.service_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    private Integer serviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public UserPrivilegeKey(Integer privilegeId, Integer deviceId, Integer serviceId) {
        this.privilegeId = privilegeId;
        this.deviceId = deviceId;
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public UserPrivilegeKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_privilege.privilege_id
     *
     * @return the value of user_privilege.privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_privilege.privilege_id
     *
     * @param privilegeId the value for user_privilege.privilege_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_privilege.device_id
     *
     * @return the value of user_privilege.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_privilege.device_id
     *
     * @param deviceId the value for user_privilege.device_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_privilege.service_id
     *
     * @return the value of user_privilege.service_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_privilege.service_id
     *
     * @param serviceId the value for user_privilege.service_id
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }
}