package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.AttackModel;
import com.loop0day.security.db.bean.AttackModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttackModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(AttackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(AttackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer vulnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(AttackModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(AttackModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<AttackModel> selectByExample(AttackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    AttackModel selectByPrimaryKey(Integer vulnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") AttackModel record, @Param("example") AttackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") AttackModel record, @Param("example") AttackModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(AttackModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_model
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(AttackModel record);
}