package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.AttackPath;
import com.loop0day.security.db.bean.AttackPathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttackPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(AttackPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(AttackPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(AttackPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(AttackPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<AttackPath> selectByExample(AttackPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    AttackPath selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") AttackPath record, @Param("example") AttackPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") AttackPath record, @Param("example") AttackPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(AttackPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attack_path
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(AttackPath record);
}