package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DeviceNetwork;
import com.loop0day.security.db.bean.DeviceNetworkExample;
import com.loop0day.security.db.bean.DeviceNetworkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceNetworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DeviceNetworkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DeviceNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DeviceNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DeviceNetwork> selectByExample(DeviceNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    DeviceNetwork selectByPrimaryKey(DeviceNetworkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceNetwork record, @Param("example") DeviceNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DeviceNetwork record, @Param("example") DeviceNetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_network
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(DeviceNetwork record);
}