package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DeviceSecurityExample;
import com.loop0day.security.db.bean.DeviceSecurityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceSecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DeviceSecurityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DeviceSecurityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DeviceSecurityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DeviceSecurityKey> selectByExample(DeviceSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceSecurityKey record, @Param("example") DeviceSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_security
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DeviceSecurityKey record, @Param("example") DeviceSecurityExample example);
}