package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DeviceConnect;
import com.loop0day.security.db.bean.DeviceConnectExample;
import com.loop0day.security.db.bean.DeviceConnectKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceConnectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DeviceConnectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DeviceConnect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DeviceConnect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DeviceConnect> selectByExample(DeviceConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    DeviceConnect selectByPrimaryKey(DeviceConnectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceConnect record, @Param("example") DeviceConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DeviceConnect record, @Param("example") DeviceConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceConnect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_connect
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(DeviceConnect record);
}