package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DeviceService;
import com.loop0day.security.db.bean.DeviceServiceExample;
import com.loop0day.security.db.bean.DeviceServiceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DeviceServiceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DeviceService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DeviceService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DeviceService> selectByExample(DeviceServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    DeviceService selectByPrimaryKey(DeviceServiceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceService record, @Param("example") DeviceServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DeviceService record, @Param("example") DeviceServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_service
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(DeviceService record);
}