package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DeviceThreat;
import com.loop0day.security.db.bean.DeviceThreatExample;
import com.loop0day.security.db.bean.DeviceThreatKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceThreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DeviceThreatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DeviceThreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DeviceThreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DeviceThreat> selectByExample(DeviceThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    DeviceThreat selectByPrimaryKey(DeviceThreatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceThreat record, @Param("example") DeviceThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DeviceThreat record, @Param("example") DeviceThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceThreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(DeviceThreat record);
}