package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DeviceDataflow;
import com.loop0day.security.db.bean.DeviceDataflowExample;
import com.loop0day.security.db.bean.DeviceDataflowKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceDataflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceDataflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceDataflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DeviceDataflowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DeviceDataflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DeviceDataflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DeviceDataflow> selectByExample(DeviceDataflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    DeviceDataflow selectByPrimaryKey(DeviceDataflowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceDataflow record, @Param("example") DeviceDataflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DeviceDataflow record, @Param("example") DeviceDataflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceDataflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_dataflow
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(DeviceDataflow record);
}