package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.Device;
import com.loop0day.security.db.bean.DeviceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    Device selectByPrimaryKey(Integer deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(Device record);
}