package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.DevicePrivilege;
import com.loop0day.security.db.bean.DevicePrivilegeExample;
import com.loop0day.security.db.bean.DevicePrivilegeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevicePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(DevicePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(DevicePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(DevicePrivilegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(DevicePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(DevicePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<DevicePrivilege> selectByExample(DevicePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    DevicePrivilege selectByPrimaryKey(DevicePrivilegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") DevicePrivilege record, @Param("example") DevicePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") DevicePrivilege record, @Param("example") DevicePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(DevicePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(DevicePrivilege record);
}