package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.SecurityVariant;
import com.loop0day.security.db.bean.SecurityVariantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityVariantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(SecurityVariantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(SecurityVariantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer variantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(SecurityVariant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(SecurityVariant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<SecurityVariant> selectByExample(SecurityVariantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    SecurityVariant selectByPrimaryKey(Integer variantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecurityVariant record, @Param("example") SecurityVariantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") SecurityVariant record, @Param("example") SecurityVariantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(SecurityVariant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_variant
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(SecurityVariant record);
}