package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.SecurityThreat;
import com.loop0day.security.db.bean.SecurityThreatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityThreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(SecurityThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(SecurityThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer threatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(SecurityThreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(SecurityThreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<SecurityThreat> selectByExample(SecurityThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    SecurityThreat selectByPrimaryKey(Integer threatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecurityThreat record, @Param("example") SecurityThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") SecurityThreat record, @Param("example") SecurityThreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(SecurityThreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_threat
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(SecurityThreat record);
}