package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.ServiceTestcase;
import com.loop0day.security.db.bean.ServiceTestcaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceTestcaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(ServiceTestcaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(ServiceTestcaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(ServiceTestcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(ServiceTestcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<ServiceTestcase> selectByExample(ServiceTestcaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    ServiceTestcase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") ServiceTestcase record, @Param("example") ServiceTestcaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") ServiceTestcase record, @Param("example") ServiceTestcaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceTestcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_testcase
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(ServiceTestcase record);
}