package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.SingleTest;
import com.loop0day.security.db.bean.SingleTestExample;
import com.loop0day.security.db.bean.SingleTestKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SingleTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(SingleTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(SingleTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(SingleTestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(SingleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(SingleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<SingleTest> selectByExample(SingleTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    SingleTest selectByPrimaryKey(SingleTestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SingleTest record, @Param("example") SingleTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") SingleTest record, @Param("example") SingleTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(SingleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_test
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByPrimaryKey(SingleTest record);
}