package com.loop0day.security.db.dao;

import com.loop0day.security.db.bean.UserPrivilegeExample;
import com.loop0day.security.db.bean.UserPrivilegeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    long countByExample(UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByExample(UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int deleteByPrimaryKey(UserPrivilegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insert(UserPrivilegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int insertSelective(UserPrivilegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    List<UserPrivilegeKey> selectByExample(UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPrivilegeKey record, @Param("example") UserPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_privilege
     *
     * @mbg.generated Wed Jun 03 17:43:21 CST 2020
     */
    int updateByExample(@Param("record") UserPrivilegeKey record, @Param("example") UserPrivilegeExample example);
}